/* slug-ui C SDK — generated by cbindgen. Do not edit by hand. */

#ifndef SLUG_UI_H
#define SLUG_UI_H

/* This file is auto-generated from slug-ui-ffi. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle to a running declarative app.
 */
typedef struct SlugUiApp SlugUiApp;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create an app from a JSON `spec` and a JSON `initial_state` object (may be
 * `"{}"` or NULL). Returns NULL on error.
 *
 * # Safety
 * `spec_json` must be a valid NUL-terminated UTF-8 string; `state_json` may be
 * NULL.
 */
SlugUiApp *slug_ui_app_new(const char *spec_json, const char *state_json);

/**
 * Return the current semantic snapshot (nodes + tools) as a JSON string.
 *
 * # Safety
 * `app` must be a handle from [`slug_ui_app_new`].
 */
char *slug_ui_snapshot_json(SlugUiApp *app);

/**
 * Perform an action on a node by ref. `args` may be NULL. Returns 0 on success,
 * -1 on error.
 *
 * # Safety
 * `app` must be a valid handle; `node_ref`/`action` valid UTF-8 strings.
 */
int slug_ui_invoke(SlugUiApp *app, const char *node_ref, const char *action, const char *args);

/**
 * Drain queued events (button presses, menu selections) as a JSON array.
 *
 * # Safety
 * `app` must be a valid handle.
 */
char *slug_ui_drain_events_json(SlugUiApp *app);

/**
 * Return the current app state as a JSON object string.
 *
 * # Safety
 * `app` must be a valid handle.
 */
char *slug_ui_state_json(SlugUiApp *app);

/**
 * Free a string returned by this library.
 *
 * # Safety
 * `s` must have been returned by one of this library's functions, and freed once.
 */
void slug_ui_string_free(char *s);

/**
 * Free an app handle.
 *
 * # Safety
 * `app` must have been returned by [`slug_ui_app_new`], and freed once.
 */
void slug_ui_app_free(SlugUiApp *app);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SLUG_UI_H */
